--- #YAML:1.0
name:               File-KeePass-Agent
version:            0.02
abstract:           Application agent for working with File::KeePass files
author:
    - Paul Seamons
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::INI:    0.01
    File::KeePass:  0.01
    IO::Prompt:     0.01
    X11::GUITest:   0.01
    X11::Protocol:  0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
